config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

  

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def show
		@user = User.find_by_profile_name(params[:id])
		if @user
			@statuses = @user.statuses.all
			render action: :show
		else
			render file: 'public/404', status: 404, formats: [:html]
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>


<% if signed_in? %>
  <div id="friend-status">
    <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
      <%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn' %>
    <% else %>
  	 <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn', id: 'add-friendship', data: { friend_id: @user.to_param } %>
    <% end %>
  </div>
<% end %>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
	<% end %>
<% end %>