config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

  

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  #attr_accessor :user, :friend

  after_destroy :delete_mutual_friendship!

  state_machine :state, initial: :pending do
  	after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]
    after_transition on: :block, do: [:block_mutual_friendship!]

    state :requested
    state :blocked

  	event :accept do
  		transition any => :accepted
  	end

    event :block do
      transition any => :blocked
    end
  end

  validate :not_blocked

  def self.request(user1, user2)
  	transaction do
	  	friendship1 = create(user: user1, friend: user2, state: 'pending')
	  	friendship2 = create(user: user2, friend: user1, state: 'requested')
 
      friendship1.send_request_email if !friendship1.new_record?
      friendship1 
  	end
  end

  def not_blocked
    if UserFriendship.exists?(user_id: user_id, friend_id: friend_id, state: 'blocked') || 
      UserFriendship.exists?(user_id: friend_id, friend_id: user_id, state: 'blocked')
      errors.add(:base, "The friendship cannot be added.")
    end
  end

  def send_request_email
  	UserNotifier.friend_requested(id).deliver_now
  end

  def send_acceptance_email
  	UserNotifier.friend_request_accepted(id).deliver_now
  end

  def mutual_friendship
    self.class.where({user_id: friend_id, friend_id: user_id}).first
  end

  def accept_mutual_friendship!
    # Get the mutual friendshp and update the state without using the state machine
    # so as not to invoke callbacks
    
    mutual_friendship.update_attribute(:state, 'accepted')
  end

  def delete_mutual_friendship!
    mutual_friendship.delete
  end

  def block_mutual_friendship!
    mutual_friendship.update_attribute(:state, 'blocked') if mutual_friendship
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  def index
    @user_friendships = UserFriendshipDecorator.decorate_collection(friendship_association.all)
    respond_with @user_friendships
  end

  def accept
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.accept!
      flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
    else
      flash[:error] = "That friendship was not accepted. They probably don't like you."
    end
    redirect_to user_friendships_path
  end

  def block
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.block!
      flash[:success] = "You have blocked #{@user_friendship.friend.first_name}."
    else
      flash[:error] = "That friendship could not be blocked."
    end
    redirect_to user_friendships_path
  end

  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      @user_friendship = UserFriendship.request(current_user, @friend)
      respond_to do |format|
        if @user_friendship.new_record?
          format.html do
            flash[:error] = "There was a problem creating that friend request."
            redirect_to profile_path(@friend)
          end
          format.json { render json: @user_friendship.to_json, status: :precondition_failed }
        else
          format.html do
            flash[:success] = "Friend request sent."
            redirect_to profile_path(@friend)
          end
          format.json { render json: @user_friendship.to_json }
        end
       end
      else
      flash[:error] = "Friend required"
      redirect_to root_path
    end
  end

  def edit
    @friend = User.where(profile_name: params[:id]).first
    @user_friendship = current_user.user_friendships.where(friend_id: @friend.id).first.decorate
  end

  def destroy
    @user_friendship = current_user.user_friendships.find(params[:id])
    if !@user_friendship.nil?
      @user_friendship.destroy
      flash[:success] = "Friendship deleted"
    else
      flash[:error] = "That friendship was not found."
    end
    redirect_to user_friendships_path
  end


  private
  def friendship_association
    case params[:list]
    when nil
      current_user.user_friendships
    when 'blocked'
      current_user.blocked_user_friendships
    when 'pending'
      current_user.pending_user_friendships
    when 'accepted'
      current_user.accepted_user_friendships
    when 'requested'
      current_user.requested_user_friendships
    end

  end
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/user_friendships/edit.html.erb
<div class="page-header">
	<h1>Viewing Friendships</h1>
</div>

<div class="row">
  <div class="avatar span2">
    <%= image_tag @user_friendship.user.gravatar_url %><br />
    <%= @user_friendship.user.first_name %>
  </div>
  <div class="avatar span2">
    <%= image_tag @user_friendship.friend.gravatar_url %><br />
    <%= @user_friendship.friend.first_name %>
  </div>
</div>
<hr />

<h3><%= @user_friendship.sub_message %></h3>

<div class="form-actions">
  <% if @user_friendship.requested? %>
    <%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship),
      method: :put do |form| %>
        <%= submit_tag "Accept Friendship", class: 'btn btn-primary' %>
      <% end %>
    <% end %>

    <%= form_for @user_friendship, url: block_user_friendship_path(@user_friendship),
      method: :put do |form| %>
        <%= submit_tag "Block Friendship", class: 'btn' %>
    <% end %>

  <%= form_for @user_friendship, url: user_friendship_path(@user_friendship),
      method: :delete do |form| %>
        <%= submit_tag "Delete Friendship", class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/user_friendships/index.html.erb
<div class="page-header">
	<h1>Friends</h1>
</div>

<div>
  <strong>Friend List</strong>
  <%= link_to 'Accepted', user_friendships_path(list: 'accepted') %>
  <%= link_to 'Requested', user_friendships_path(list: 'requested') %>
  <%= link_to 'Pending', user_friendships_path(list: 'pending') %>
  <%= link_to 'Blocked', user_friendships_path(list: 'blocked') %>
</div>

<% @user_friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="span1">
      <%= link_to image_tag(friend.gravatar_url), profile_path(friend) %>
    </div>
    <div class="span7">
      <strong><%= friend.full_name %></strong><br />
        <% if friendship.pending? %>
          <em>Friendship is pending.</em> <%= link_to "Delete request",
            edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
        <% if friendship.requested? %>
          <em>Friendship requested.</em> <%= link_to "Accept Friendship",
            edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
        <% if friendship.accepted? %>
          <em>Friendship begun <%= friendship.updated_at %>.</em> <%= link_to "Update
          friendship", edit_user_friendship_path(friendship.friend.profile_name) %>.
        <% end %>
    </div>
  </div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.full_name %></h1>

  <p>Are you SURE you want to friend that dweeb <%= @friend.full_name %>?</p>

  <%= form_for @user_friendship, method: :post do |form| %>
    <div class="form form-actions">
      <%= form.hidden_field :friend_id, value: @friend.profile_name %>
      <%= submit_tag "Yes, Add Dwee...I Mean, Friend", class: 'btn btn-primary' %>
      <%= link_to "On Second Thought...", profile_path(@friend), class: 'btn' %>
    </div>
  <% end %>
<% end %>