config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otterbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a href="#" class="brand">OtterBook</a>
			<ul class="nav">
				<li><%= link_to "All Statuses", feed_path %></li>
			</ul>
			<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to 'Friends', user_friendships_path %></li>
						<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log Out", logout_path %></li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>

				</ul>
		</div>
	</div>
</div>			
	<div class="container">
		<% flash.each do |type, message| %>
			div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
			</div>
		<% end %>
	<%= yield %>
	</div>

</body>
</html>